# Generated by Django 5.2.4 on 2026-09-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0002_alter_user_id'),
        ('userManager', '0002_alter_user_managers_alter_user_avatar_alter_user_id_and_more'),
    ]

    operations = [
    ]
