# Generated by Django 5.2.4 on 2026-09-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projectManager", "0003_alter_project_id_alter_skill_id"),
        ("userManager", "0003_merge_20260904_1100"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="owned_projects",
            field=models.ManyToManyField(
                related_name="owned_projects", to="projectManager.project"
            ),
        ),
    ]
