# Generated by Django 5.2.4 on 2026-09-05 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userManager", "0005_user_date_joined"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="owned_projects",
        ),
    ]
