# Generated by Django 5.2.4 on 2026-09-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userManager", "0006_remove_user_owned_projects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
