# Generated by Django 5.2.4 on 2026-09-05 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userManager", "0007_alter_user_date_joined"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="github",
            new_name="github_url",
        ),
    ]
