# Generated by Django 5.2.4 on 2026-09-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projectManager", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="skill",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
