# Generated by Django 5.2.4 on 2026-09-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projectManager", "0003_alter_project_id_alter_skill_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="skills",
            field=models.ManyToManyField(
                related_name="skills", to="projectManager.skill"
            ),
        ),
    ]
