# Generated by Django 5.2.4 on 2026-09-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projectManager", "0005_alter_project_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
